services:
  focal:
    hostname: plnx-21
    image: private/petalinux:focal
    build:
      context: .
      args:
        - USER
        - CODENAME=focal
    ports:
      - 52004:22
    volumes:
      - /home/${USER}/petalinux:/home/${USER}/petalinux
      - /tools/Xilinx:/tools/Xilinx
      - /tools/Xilinx/sswreleases/2021.2:/home/${USER}/.plnx/2021.2
      - ./envs/plnx21.sh:/home/${USER}/.bash_aliases
      - tftpboot:/tftpboot

  jammy:
    hostname: plnx-23
    image: private/petalinux:jammy
    build:
      context: .
      args:
        - USER
        - CODENAME=jammy
    ports:
      - 52204:22
    volumes:
      - /home/${USER}/petalinux:/home/${USER}/petalinux
      - /tools/Xilinx:/tools/Xilinx
      - /tools/Xilinx/sswreleases/2023.2:/home/${USER}/.plnx/2023.2
      - ./envs/plnx23.sh:/home/${USER}/.bash_aliases
      - tftpboot:/tftpboot

  tftpd:
    hostname: tftpd
    image: private/tftpd
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache tftp-hpa
    command: in.tftpd --foreground -v
    ports:
      - 69:69/udp
    volumes:
      - tftpboot:/tftpboot

volumes:
  tftpboot:
    driver: tftpboot
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=512M,uid=1000,gid=1000
